export const propertyTypeToApi = {
  CASA: "HOUSE",
  DEPARTAMENTO: "APARTMENT",
  PH: "PH",

  DUPLEX: "DUPLEX",
  TRIPLEX: "TRIPLEX",

  TERRENO: "LAND",
  LOTE: "LOT",

  QUINTA: "QUINTA",
  CHACRA: "CHACRA",
  CAMPO: "FARM",

  LOCAL: "LOCAL",
  OFICINA: "OFFICE",
  CONSULTORIO: "CONSULTING_ROOM",

  GALPON: "WAREHOUSE",
  DEPOSITO: "STORAGE",

  GARAJE: "GARAGE",

  EDIFICIO: "BUILDING",
} as const;

export const propertyTypeToUI = {
  HOUSE: "CASA",
  APARTMENT: "DEPARTAMENTO",
  PH: "PH",

  DUPLEX: "DUPLEX",
  TRIPLEX: "TRIPLEX",

  LAND: "TERRENO",
  LOT: "LOTE",

  QUINTA: "QUINTA",
  CHACRA: "CHACRA",
  FARM: "CAMPO",

  LOCAL: "LOCAL",
  OFFICE: "OFICINA",
  CONSULTING_ROOM: "CONSULTORIO",

  WAREHOUSE: "GALPON",
  STORAGE: "DEPOSITO",

  GARAGE: "GARAJE",

  BUILDING: "EDIFICIO",
} as const;